//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// All objects in the database
    /// </summary>
    public partial class DBA_OBJECTS : ICloneable, INotifyPropertyChanged    {

        public DBA_OBJECTS()
        {
        }

        #region Properties
    
        /// <summary>
        /// Username of the owner of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OWNER
        {
            get
            {
                return _OWNER;
            }
            set
            {
                if (_OWNER != value)
                {
                    _OWNER = value;
                    OnPropertyChanged("OWNER");
                }
            }
        }
        private string _OWNER;

    
        /// <summary>
        /// Name of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OBJECT_NAME
        {
            get
            {
                return _OBJECT_NAME;
            }
            set
            {
                if (_OBJECT_NAME != value)
                {
                    _OBJECT_NAME = value;
                    OnPropertyChanged("OBJECT_NAME");
                }
            }
        }
        private string _OBJECT_NAME;

    
        /// <summary>
        /// Name of the sub-object (for example, partititon)
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string SUBOBJECT_NAME
        {
            get
            {
                return _SUBOBJECT_NAME;
            }
            set
            {
                if (_SUBOBJECT_NAME != value)
                {
                    _SUBOBJECT_NAME = value;
                    OnPropertyChanged("SUBOBJECT_NAME");
                }
            }
        }
        private string _SUBOBJECT_NAME;

    
        /// <summary>
        /// Object number of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual decimal OBJECT_ID
        {
            get
            {
                return _OBJECT_ID;
            }
            set
            {
                if (_OBJECT_ID != value)
                {
                    _OBJECT_ID = value;
                    OnPropertyChanged("OBJECT_ID");
                }
            }
        }
        private decimal _OBJECT_ID;

    
        /// <summary>
        /// Object number of the segment which contains the object
        /// </summary>
        public virtual global::System.Nullable<decimal> DATA_OBJECT_ID
        {
            get
            {
                return _DATA_OBJECT_ID;
            }
            set
            {
                if (_DATA_OBJECT_ID != value)
                {
                    _DATA_OBJECT_ID = value;
                    OnPropertyChanged("DATA_OBJECT_ID");
                }
            }
        }
        private global::System.Nullable<decimal> _DATA_OBJECT_ID;

    
        /// <summary>
        /// Type of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(19)]
        public virtual string OBJECT_TYPE
        {
            get
            {
                return _OBJECT_TYPE;
            }
            set
            {
                if (_OBJECT_TYPE != value)
                {
                    _OBJECT_TYPE = value;
                    OnPropertyChanged("OBJECT_TYPE");
                }
            }
        }
        private string _OBJECT_TYPE;

    
        /// <summary>
        /// Timestamp for the creation of the object
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> CREATED
        {
            get
            {
                return _CREATED;
            }
            set
            {
                if (_CREATED != value)
                {
                    _CREATED = value;
                    OnPropertyChanged("CREATED");
                }
            }
        }
        private global::System.Nullable<System.DateTime> _CREATED;

    
        /// <summary>
        /// Timestamp for the last DDL change (including GRANT and REVOKE) to the object
        /// </summary>
        public virtual global::System.Nullable<System.DateTime> LAST_DDL_TIME
        {
            get
            {
                return _LAST_DDL_TIME;
            }
            set
            {
                if (_LAST_DDL_TIME != value)
                {
                    _LAST_DDL_TIME = value;
                    OnPropertyChanged("LAST_DDL_TIME");
                }
            }
        }
        private global::System.Nullable<System.DateTime> _LAST_DDL_TIME;

    
        /// <summary>
        /// Timestamp for the specification of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(19)]
        public virtual string TIMESTAMP
        {
            get
            {
                return _TIMESTAMP;
            }
            set
            {
                if (_TIMESTAMP != value)
                {
                    _TIMESTAMP = value;
                    OnPropertyChanged("TIMESTAMP");
                }
            }
        }
        private string _TIMESTAMP;

    
        /// <summary>
        /// Status of the object
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(7)]
        public virtual string STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                if (_STATUS != value)
                {
                    _STATUS = value;
                    OnPropertyChanged("STATUS");
                }
            }
        }
        private string _STATUS;

    
        /// <summary>
        /// Can the current session only see data that it place in this object itself?
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string TEMPORARY
        {
            get
            {
                return _TEMPORARY;
            }
            set
            {
                if (_TEMPORARY != value)
                {
                    _TEMPORARY = value;
                    OnPropertyChanged("TEMPORARY");
                }
            }
        }
        private string _TEMPORARY;

    
        /// <summary>
        /// Was the name of this object system generated?
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string GENERATED
        {
            get
            {
                return _GENERATED;
            }
            set
            {
                if (_GENERATED != value)
                {
                    _GENERATED = value;
                    OnPropertyChanged("GENERATED");
                }
            }
        }
        private string _GENERATED;

    
        /// <summary>
        /// Is this a secondary object created as part of icreate for domain indexes?
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string SECONDARY
        {
            get
            {
                return _SECONDARY;
            }
            set
            {
                if (_SECONDARY != value)
                {
                    _SECONDARY = value;
                    OnPropertyChanged("SECONDARY");
                }
            }
        }
        private string _SECONDARY;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_OBJECTS obj = new DBA_OBJECTS();
            obj.OWNER = OWNER;
            obj.OBJECT_NAME = OBJECT_NAME;
            obj.SUBOBJECT_NAME = SUBOBJECT_NAME;
            obj.OBJECT_ID = OBJECT_ID;
            obj.DATA_OBJECT_ID = DATA_OBJECT_ID;
            obj.OBJECT_TYPE = OBJECT_TYPE;
            obj.CREATED = CREATED;
            obj.LAST_DDL_TIME = LAST_DDL_TIME;
            obj.TIMESTAMP = TIMESTAMP;
            obj.STATUS = STATUS;
            obj.TEMPORARY = TEMPORARY;
            obj.GENERATED = GENERATED;
            obj.SECONDARY = SECONDARY;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
