//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// All scheduler classes in the database
    /// </summary>
    public partial class DBA_SCHEDULER_JOB_CLASSES : ICloneable, INotifyPropertyChanged    {

        public DBA_SCHEDULER_JOB_CLASSES()
        {
        }

        #region Properties
    
        /// <summary>
        /// Name of the scheduler class
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string JOB_CLASS_NAME
        {
            get
            {
                return _JOB_CLASS_NAME;
            }
            set
            {
                if (_JOB_CLASS_NAME != value)
                {
                    _JOB_CLASS_NAME = value;
                    OnPropertyChanged("JOB_CLASS_NAME");
                }
            }
        }
        private string _JOB_CLASS_NAME;

    
        /// <summary>
        /// Resource consumer group associated with the class
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public virtual string RESOURCE_CONSUMER_GROUP
        {
            get
            {
                return _RESOURCE_CONSUMER_GROUP;
            }
            set
            {
                if (_RESOURCE_CONSUMER_GROUP != value)
                {
                    _RESOURCE_CONSUMER_GROUP = value;
                    OnPropertyChanged("RESOURCE_CONSUMER_GROUP");
                }
            }
        }
        private string _RESOURCE_CONSUMER_GROUP;

    
        /// <summary>
        /// Name of the service this class is affined with
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(64)]
        public virtual string SERVICE
        {
            get
            {
                return _SERVICE;
            }
            set
            {
                if (_SERVICE != value)
                {
                    _SERVICE = value;
                    OnPropertyChanged("SERVICE");
                }
            }
        }
        private string _SERVICE;

    
        /// <summary>
        /// Amount of logging that will be done pertaining to this class
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(4)]
        public virtual string LOGGING_LEVEL
        {
            get
            {
                return _LOGGING_LEVEL;
            }
            set
            {
                if (_LOGGING_LEVEL != value)
                {
                    _LOGGING_LEVEL = value;
                    OnPropertyChanged("LOGGING_LEVEL");
                }
            }
        }
        private string _LOGGING_LEVEL;

    
        /// <summary>
        /// The history to maintain in the job log (in days) for this class
        /// </summary>
        public virtual global::System.Nullable<decimal> LOG_HISTORY
        {
            get
            {
                return _LOG_HISTORY;
            }
            set
            {
                if (_LOG_HISTORY != value)
                {
                    _LOG_HISTORY = value;
                    OnPropertyChanged("LOG_HISTORY");
                }
            }
        }
        private global::System.Nullable<decimal> _LOG_HISTORY;

    
        /// <summary>
        /// Comments on this class
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(240)]
        public virtual string COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                if (_COMMENTS != value)
                {
                    _COMMENTS = value;
                    OnPropertyChanged("COMMENTS");
                }
            }
        }
        private string _COMMENTS;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_SCHEDULER_JOB_CLASSES obj = new DBA_SCHEDULER_JOB_CLASSES();
            obj.JOB_CLASS_NAME = JOB_CLASS_NAME;
            obj.RESOURCE_CONSUMER_GROUP = RESOURCE_CONSUMER_GROUP;
            obj.SERVICE = SERVICE;
            obj.LOGGING_LEVEL = LOGGING_LEVEL;
            obj.LOG_HISTORY = LOG_HISTORY;
            obj.COMMENTS = COMMENTS;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
