//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// All Roles which exist in the database
    /// </summary>
    public partial class DBA_ROLES : ICloneable, INotifyPropertyChanged    {

        public DBA_ROLES()
        {
        }

        #region Properties
    
        /// <summary>
        /// Role Name
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string ROLE
        {
            get
            {
                return _ROLE;
            }
            set
            {
                if (_ROLE != value)
                {
                    _ROLE = value;
                    OnPropertyChanged("ROLE");
                }
            }
        }
        private string _ROLE;

    
        /// <summary>
        /// Indicates if the role requires a password to be enabled
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(8)]
        public virtual string PASSWORD_REQUIRED
        {
            get
            {
                return _PASSWORD_REQUIRED;
            }
            set
            {
                if (_PASSWORD_REQUIRED != value)
                {
                    _PASSWORD_REQUIRED = value;
                    OnPropertyChanged("PASSWORD_REQUIRED");
                }
            }
        }
        private string _PASSWORD_REQUIRED;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_ROLES obj = new DBA_ROLES();
            obj.ROLE = ROLE;
            obj.PASSWORD_REQUIRED = PASSWORD_REQUIRED;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
