//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// Comments on all materialized views in the database
    /// </summary>
    public partial class DBA_MVIEW_COMMENTS : ICloneable, INotifyPropertyChanged    {

        public DBA_MVIEW_COMMENTS()
        {
        }

        #region Properties
    
        /// <summary>
        /// Owner of the materialized view
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OWNER
        {
            get
            {
                return _OWNER;
            }
            set
            {
                if (_OWNER != value)
                {
                    _OWNER = value;
                    OnPropertyChanged("OWNER");
                }
            }
        }
        private string _OWNER;

    
        /// <summary>
        /// Name of the materialized view
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string MVIEW_NAME
        {
            get
            {
                return _MVIEW_NAME;
            }
            set
            {
                if (_MVIEW_NAME != value)
                {
                    _MVIEW_NAME = value;
                    OnPropertyChanged("MVIEW_NAME");
                }
            }
        }
        private string _MVIEW_NAME;

    
        /// <summary>
        /// Comment on the materialized view
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(4000)]
        public virtual string COMMENTS
        {
            get
            {
                return _COMMENTS;
            }
            set
            {
                if (_COMMENTS != value)
                {
                    _COMMENTS = value;
                    OnPropertyChanged("COMMENTS");
                }
            }
        }
        private string _COMMENTS;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_MVIEW_COMMENTS obj = new DBA_MVIEW_COMMENTS();
            obj.OWNER = OWNER;
            obj.MVIEW_NAME = MVIEW_NAME;
            obj.COMMENTS = COMMENTS;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
