//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// Tablespace quotas for all users
    /// </summary>
    public partial class DBA_TS_QUOTAS : ICloneable, INotifyPropertyChanged    {

        public DBA_TS_QUOTAS()
        {
        }

        #region Properties
    
        /// <summary>
        /// Tablespace name
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string TABLESPACE_NAME
        {
            get
            {
                return _TABLESPACE_NAME;
            }
            set
            {
                if (_TABLESPACE_NAME != value)
                {
                    _TABLESPACE_NAME = value;
                    OnPropertyChanged("TABLESPACE_NAME");
                }
            }
        }
        private string _TABLESPACE_NAME;

    
        /// <summary>
        /// User with resource rights on the tablespace
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                if (_USERNAME != value)
                {
                    _USERNAME = value;
                    OnPropertyChanged("USERNAME");
                }
            }
        }
        private string _USERNAME;

    
        /// <summary>
        /// Number of bytes charged to the user
        /// </summary>
        public virtual global::System.Nullable<decimal> BYTES
        {
            get
            {
                return _BYTES;
            }
            set
            {
                if (_BYTES != value)
                {
                    _BYTES = value;
                    OnPropertyChanged("BYTES");
                }
            }
        }
        private global::System.Nullable<decimal> _BYTES;

    
        /// <summary>
        /// User's quota in bytes.  NULL if no limit
        /// </summary>
        public virtual global::System.Nullable<decimal> MAX_BYTES
        {
            get
            {
                return _MAX_BYTES;
            }
            set
            {
                if (_MAX_BYTES != value)
                {
                    _MAX_BYTES = value;
                    OnPropertyChanged("MAX_BYTES");
                }
            }
        }
        private global::System.Nullable<decimal> _MAX_BYTES;

    
        /// <summary>
        /// Number of ORACLE blocks charged to the user
        /// </summary>
        public virtual global::System.Nullable<decimal> BLOCKS
        {
            get
            {
                return _BLOCKS;
            }
            set
            {
                if (_BLOCKS != value)
                {
                    _BLOCKS = value;
                    OnPropertyChanged("BLOCKS");
                }
            }
        }
        private global::System.Nullable<decimal> _BLOCKS;

    
        /// <summary>
        /// User's quota in ORACLE blocks.  NULL if no limit
        /// </summary>
        public virtual global::System.Nullable<decimal> MAX_BLOCKS
        {
            get
            {
                return _MAX_BLOCKS;
            }
            set
            {
                if (_MAX_BLOCKS != value)
                {
                    _MAX_BLOCKS = value;
                    OnPropertyChanged("MAX_BLOCKS");
                }
            }
        }
        private global::System.Nullable<decimal> _MAX_BLOCKS;

    
        /// <summary>
        /// Whether the tablespace has been dropped
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(3)]
        public virtual string DROPPED
        {
            get
            {
                return _DROPPED;
            }
            set
            {
                if (_DROPPED != value)
                {
                    _DROPPED = value;
                    OnPropertyChanged("DROPPED");
                }
            }
        }
        private string _DROPPED;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_TS_QUOTAS obj = new DBA_TS_QUOTAS();
            obj.TABLESPACE_NAME = TABLESPACE_NAME;
            obj.USERNAME = USERNAME;
            obj.BYTES = BYTES;
            obj.MAX_BYTES = MAX_BYTES;
            obj.BLOCKS = BLOCKS;
            obj.MAX_BLOCKS = MAX_BLOCKS;
            obj.DROPPED = DROPPED;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
