//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// Information about accessible columns in constraint definitions
    /// </summary>
    public partial class DBA_CONS_COLUMNS : ICloneable, INotifyPropertyChanged    {

        public DBA_CONS_COLUMNS()
        {
        }

        #region Properties
    
        /// <summary>
        /// Owner of the constraint definition
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OWNER
        {
            get
            {
                return _OWNER;
            }
            set
            {
                if (_OWNER != value)
                {
                    _OWNER = value;
                    OnPropertyChanged("OWNER");
                }
            }
        }
        private string _OWNER;

    
        /// <summary>
        /// Name associated with the constraint definition
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string CONSTRAINT_NAME
        {
            get
            {
                return _CONSTRAINT_NAME;
            }
            set
            {
                if (_CONSTRAINT_NAME != value)
                {
                    _CONSTRAINT_NAME = value;
                    OnPropertyChanged("CONSTRAINT_NAME");
                }
            }
        }
        private string _CONSTRAINT_NAME;

    
        /// <summary>
        /// Name associated with table with constraint definition
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string TABLE_NAME
        {
            get
            {
                return _TABLE_NAME;
            }
            set
            {
                if (_TABLE_NAME != value)
                {
                    _TABLE_NAME = value;
                    OnPropertyChanged("TABLE_NAME");
                }
            }
        }
        private string _TABLE_NAME;

    
        /// <summary>
        /// Name associated with column or attribute of object column specified in the constraint definition
        /// </summary>
        [System.ComponentModel.DataAnnotations.StringLength(4000)]
        public virtual string COLUMN_NAME
        {
            get
            {
                return _COLUMN_NAME;
            }
            set
            {
                if (_COLUMN_NAME != value)
                {
                    _COLUMN_NAME = value;
                    OnPropertyChanged("COLUMN_NAME");
                }
            }
        }
        private string _COLUMN_NAME;

    
        /// <summary>
        /// Original position of column or attribute in definition
        /// </summary>
        public virtual global::System.Nullable<decimal> POSITION
        {
            get
            {
                return _POSITION;
            }
            set
            {
                if (_POSITION != value)
                {
                    _POSITION = value;
                    OnPropertyChanged("POSITION");
                }
            }
        }
        private global::System.Nullable<decimal> _POSITION;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_CONS_COLUMNS obj = new DBA_CONS_COLUMNS();
            obj.OWNER = OWNER;
            obj.CONSTRAINT_NAME = CONSTRAINT_NAME;
            obj.TABLE_NAME = TABLE_NAME;
            obj.COLUMN_NAME = COLUMN_NAME;
            obj.POSITION = POSITION;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
