//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 07.07.2015 09:05:24
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;

namespace EFModel.DataDictionary
{

    /// <summary>
    /// There are no comments for EFModel.DataDictionary.DBA_SUBPART_KEY_COLUMNS in the schema.
    /// </summary>
    public partial class DBA_SUBPART_KEY_COLUMNS : ICloneable, INotifyPropertyChanged    {

        public DBA_SUBPART_KEY_COLUMNS()
        {
        }

        #region Properties
    
        /// <summary>
        /// There are no comments for OWNER in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OWNER
        {
            get
            {
                return _OWNER;
            }
            set
            {
                if (_OWNER != value)
                {
                    _OWNER = value;
                    OnPropertyChanged("OWNER");
                }
            }
        }
        private string _OWNER;

    
        /// <summary>
        /// There are no comments for NAME in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                if (_NAME != value)
                {
                    _NAME = value;
                    OnPropertyChanged("NAME");
                }
            }
        }
        private string _NAME;

    
        /// <summary>
        /// There are no comments for OBJECT_TYPE in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(5)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string OBJECT_TYPE
        {
            get
            {
                return _OBJECT_TYPE;
            }
            set
            {
                if (_OBJECT_TYPE != value)
                {
                    _OBJECT_TYPE = value;
                    OnPropertyChanged("OBJECT_TYPE");
                }
            }
        }
        private string _OBJECT_TYPE;

    
        /// <summary>
        /// There are no comments for COLUMN_NAME in the schema.
        /// </summary>
        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(4000)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string COLUMN_NAME
        {
            get
            {
                return _COLUMN_NAME;
            }
            set
            {
                if (_COLUMN_NAME != value)
                {
                    _COLUMN_NAME = value;
                    OnPropertyChanged("COLUMN_NAME");
                }
            }
        }
        private string _COLUMN_NAME;

    
        /// <summary>
        /// There are no comments for COLUMN_POSITION in the schema.
        /// </summary>
        public virtual global::System.Nullable<decimal> COLUMN_POSITION
        {
            get
            {
                return _COLUMN_POSITION;
            }
            set
            {
                if (_COLUMN_POSITION != value)
                {
                    _COLUMN_POSITION = value;
                    OnPropertyChanged("COLUMN_POSITION");
                }
            }
        }
        private global::System.Nullable<decimal> _COLUMN_POSITION;


        #endregion
    
        #region ICloneable Members

        public virtual object Clone()
        {
            DBA_SUBPART_KEY_COLUMNS obj = new DBA_SUBPART_KEY_COLUMNS();
            obj.OWNER = OWNER;
            obj.NAME = NAME;
            obj.OBJECT_TYPE = OBJECT_TYPE;
            obj.COLUMN_NAME = COLUMN_NAME;
            obj.COLUMN_POSITION = COLUMN_POSITION;
            return obj;
        }

        #endregion
    
        #region INotifyPropertyChanged Members

        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged(string propertyName) {

          if (PropertyChanged != null)
            PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }

        #endregion
    }

}
